site_name: Kosmos-Meteor [SpaceApps 2025 Project - Meteor Madness] 
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Add this section to link your custom CSS
  extra_css:
    - stylesheets/extra.css

# Correctly configured markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.superfences:
      # This configuration tells superfences how to handle 'mermaid' code blocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  # Ensure mermaid2 is NOT in this list
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
            docstring_style: google



nav:
  - Home: index.md
  - Project Structure: project_structure.md
  - Data Flow: data_flow.md
  - API Reference:
    - Core: api/core.md
    - Simulation: api/simulation.md